### ISSUE TITLE
Couldn't create a Linode instance in Tokyo DC?

### ISSUE THREAD

**Issue by jimmychu0807** [displague/vagrant-linode#24]
Hi,

I am trying out Vagrant Linode API to automate my server deployment. I can run with the config in the README, with DC set to Newark, but not able to create a new instance in Tokyo.

It returns me:
```
.../.vagrant.d/gems/gems/linode-0.8.1/lib/linode.rb:82:in `send_request': Errors completing request [linode.create] @ [https://api.linode.com/] with data [{:planid=>2, :datacenterid=>8, :paymentterm=>"1"}]: (RuntimeError)
  - Error #8 - No open slots for this plan!.  (Please consult https://www.linode.com/api/linode/linode.create)
```

It will be great if Tokyo DC also support using Vagrant for provisioning. Btw, great work for the project. I would really love this feature/component if it works.

Btw, one reason I choose Linode Tokyo DC is because it has much faster connection speed from China than Digital Ocean Singapore server. So kudo to the underlying DC infrastructure work.

**Comment by displague** [comment]
Vagrant-Linode provisioning works with all of the datacenters, however, Linode has sold-out of Tokyo space for new Linodes.  They have announced other datacenter launches.

- https://www.linode.com/linodes#features-dc-container
- https://blog.linode.com/2015/01/16/linode-datacenter-expansion/

I'm not sure if I should process the API error you received and return something more human.

**Comment by jimmychu0807** [comment]
I see. Good to know the business is going well with Linode. I thought this was something about how the API talking to the underlying datacenter. Apparently it is returning the right information. I am closing this one then.

**Comment by displague** [comment]
https://github.com/displague/vagrant-linode/commit/128ee6c71a0d6ea89e82af2138f56c1855a468dd
