### ISSUE TITLE
Setting linode label with provider.label.  Document?

### ISSUE THREAD

**Issue by cmawhorter** [displague/vagrant-linode#28]
The linode label defaults to "default" but can be seemingly overridden by setting `provider.label` in the Vagrantfile.  

I was able to do `provider.label = 'whatever'` and it created a new linode with the label "whatever".

Should this be added to [the documentation](https://github.com/displague/vagrant-linode#configure)?

**Comment by displague** [comment]
Added - thanks! https://github.com/displague/vagrant-linode/compare/90dedae%5E1...36d2f33eb6345771e0076def144a73f2d5227392
