### ISSUE TITLE
possible error with disk labels

### ISSUE THREAD

**Issue by displague** [displague/vagrant-linode#36]
I couldn't reproduce this from a fresh Linode or even the same Linode after a few hours had passed, but for about an hour I got this error while trying to bring up this particular disk.  I ran `destroy -f` prior to this command.

```
$ vagrant up dev3-dallas
Bringing machine 'dev3-dallas' up with 'linode' provider...
==> dev3-dallas: Creating a new linode...
==> dev3-dallas: Created a new linode... 1138716
/Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:85:in `parse': API Error on linode.disk.create: [{"ERRORCODE"=>6, "ERRORMESSAGE"=>"Label is required but was not passed in"}] (RuntimeError)
	from /Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:79:in `error_check'
	from /Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:71:in `call'
	from /Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:62:in `block in make_call'
	from /Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:63:in `make_call'
	from /Users/marques/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:44:in `method_missing'
	from /Users/marques/.vagrant.d/gems/gems/vagrant-linode-0.1.3/lib/vagrant-linode/actions/create.rb:97:in `call'
```

https://gist.github.com/displague/1605285f0bf8fe4a251e

**Comment by displague** [comment]
I hit this again.  Destroying and recreating the Linode worked around the problem.  Probably something on the other side of the API.

**Comment by Spriz** [comment]
I got this one too...

```
➜  linode-php56 git:(master) ✗ vagrant up
Bringing machine 'default' up with 'linode' provider...
==> default: Linode has not been created
==> default: Creating a new linode...
==> default: Created a new linode... 1401128
/Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:85:in `parse': API Error on linode.disk.create: [{"ERRORCODE"=>6, "ERRORMESSAGE"=>"Label is required but was not passed in"}] (RuntimeError)
	from /Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:79:in `error_check'
	from /Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:71:in `call'
	from /Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:62:in `block in make_call'
	from /Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:63:in `make_call'
	from /Users/spriz/.vagrant.d/gems/gems/linodeapi-0.1.1/lib/linodeapi/raw.rb:44:in `method_missing'
	from /Users/spriz/.vagrant.d/gems/gems/vagrant-linode-0.2.0/lib/vagrant-linode/actions/create.rb:97:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/spriz/.vagrant.d/gems/gems/vagrant-linode-0.2.0/lib/vagrant-linode/actions/connect_linode.rb:31:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /Users/spriz/.vagrant.d/gems/gems/vagrant-linode-0.2.0/lib/vagrant-linode/actions/message_not_created.rb:11:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by mgkimsal** [comment]
getting the same issue as @Spriz

**Comment by jtreminio** [comment]
Any news on this? Can't spin up a new box use linodeapi-1.0.0:

    API Error on linode.disk.create: [{"ERRORCODE"=>6, "ERRORMESSAGE"=>"Label is required but was not passed in"}]

**Comment by displague** [comment]
@akerl Do you suppose this could be related to the API flapping behavior seen earlier today?  Does [linodeapi](https://www.github.com/akerl/linodeapi) cache the spec?

**Comment by akerl** [comment]
linodeapi has pulled the spec live at runtime for a while (I believe since 0.6.0), so the only caching would be within a single vagrant command invocation.

The error that @jtreminio pasted is exactly the error I hit earlier today, where the API was sometimes returning api.spec data that was missing the Label and other params from several disk-related calls, but the actual calls still knew to require those params.

**Comment by displague** [comment]
The problem is definitely upstream, on the API itself.

@akerl Would you consider including the spec in the gem and having an option to initialize from the local version vs the live copy?  This would save a round trip in any communication (which may reduce the frequency of rate limitted responses).  Under this particular circumstance the problem would be averted.

```
$ brew install httpie jq
# this currently yields different results when repeated
$ http 'https://api.linode.com/?api_action=api.spec' | jq '.DATA.METHODS."linode.disk.create"'
```
```json
{
  "DESCRIPTION": "",
  "PARAMETERS": {
    "rootSSHKey": {
      "NAME": "rootSSHKey",
      "DESCRIPTION": "",
      "default": "",
      "TYPE": "string",
      "REQUIRED": false
    },
    "LinodeID": {
      "NAME": "LinodeID",
      "DESCRIPTION": "",
      "TYPE": "numeric",
      "REQUIRED": true
    },
    "FromDistributionID": {
      "NAME": "FromDistributionID",
      "DESCRIPTION": "",
      "default": 0,
      "TYPE": "numeric",
      "REQUIRED": false
    },
    "rootPass": {
      "NAME": "rootPass",
      "DESCRIPTION": "",
      "default": "",
      "TYPE": "string",
      "REQUIRED": false
    }
  },
  "THROWS": "NOTFOUND,VALIDATION"
}
```

**Comment by akerl** [comment]
In fairness, my initial response is: the API shouldn't be returning invalid API specs. That it does so isn't something that the API gem can be reasonably expected to handle. I, as an informed human, know that linode.disk.create needs a label, but I could have just as easily merged an update to the cached spec that removed those calls, meaning even a cached spec would be invalid.

I used to use a cached spec, but the round trip of 1 api.spec call ended up being cheap compared to having to release an update to the gem every time the spec changed.

I'd suggest the following:

* Linode's API shouldn't be returning bogus data for a portion of api.spec calls. To be clear, I'm not calling this out because I think you disagree, but to confirm that as an API wrapper author, this is a critical issue that impacts my ability to work with the API.
* The api.spec call returns a version parameter. If the version parameter started being incremented when the API was changed, I could do saner tracking of updates with https://github.com/akerl/prospectus/ to track when the spec changed
* In a world where tracking API changes was saner, I could see locking a patch release to an API spec cached in the gem, with an option to force "live-mode" and pull the current spec at runtime.

**Comment by displague** [comment]
That's totally understandable.  The version number hasn't been rotated despite several visible changes.  It would be a very convenient versioning target if it were.

**Comment by displague** [comment]
This problem has been rectified on the Linode API side.  I'm closing this issue.  

If anyone ever sees this particular error message again they should grab the output of the `http ... | jq ...` command above.  It could highlight the problem.

Heads up - there will be API maintenance during this weekend.  http://status.linode.com/incidents/hmnhcljndjlc

Thanks for your patience.
