### ISSUE TITLE
api_key doesn't work; token does

### ISSUE THREAD

**Issue by wluxion** [displague/vagrant-linode#37]
I kept getting: raw.rb:85:in `parse': API Error on linode.list: [{"ERRORCODE"=>4, "ERRORMESSAGE"=>"Authentication failed"}] (RuntimeError)

I thought this was related to certificate issues, but after working through all the guides, I still couldn't fix it. On a whim, I tried using the token parameter instead of api_key, and that worked.

Didn't work:
```
provider.api_key = 'XXXXXXX'
```
Worked:
```
provider.token = 'XXXXXXX'
```

**Comment by displague** [comment]
The gem hasn't been updated to match master yet, the docs are revealing master.

I'll give it a version bump later today.

**Comment by displague** [comment]
v0.2.0 is available now and introduces this option
