### ISSUE TITLE
Rebuild fails

### ISSUE THREAD

**Issue by roozbehf** [displague/vagrant-linode#42]
Vagrant 'rebuild' fails, while the documentation claims that it is supported. I am not familiar with Ruby but looking at the code, it seems like that the failure is intended, no?

1) is there any work around?
2) should the README file be updated accordingly?

**Comment by displague** [comment]
It's not implemented.  I've been reluctant to implement a rebuild but I think the time has come.

It should follow this behavior:
https://www.linode.com/docs/troubleshooting/rescue-and-rebuild#erasing-everything-and-starting-over

and essentially recreate the linode, without changing the plan, reuse the disk and config that was used during install, and reinstall the distribution and provision according to the vagrant config.

This should not be confused with http://docs.vagrantup.com/v2/getting-started/rebuild.html (`vagrant up`)

Thoughts?

**Comment by displague** [comment]
If that's the behavior you are looking for, you can still `vagrant destroy` and `vagrant up` for mostly the same effect.  You will end up with a different IP and LinodeID.

**Comment by roozbehf** [comment]
Yes, that's the behaviour I am looking for. The main reason being: I want to keep the IP addresses. 

In fact I found this problem a bit challenging: in public Clouds, I want to be able to automatically create a network of machines, provision them, and every now and then destroy the machines and rebuild them keeping their ip addresses (e.g., wrt DNS setups, and so). In the case of Vagrant and Linode, I thought the 'rebuild' command is the solution, but sadly found it not implemented. :-) 

Thanks anyways for looking into this. I am not confident to implement it myself in Ruby, otherwise I would have loved to do so. My Ruby experience is very basic.

**Comment by displague** [comment]
Rebuild support has been merged in https://github.com/displague/vagrant-linode/pull/67 but it will take some reworking before I include this in a versioned release.

**Comment by displague** [comment]
Rebuild has been around for a few versions since I last replied, but it is certainly in v0.3.0.
