### ISSUE TITLE
vagrant-linode install fails on osx

### ISSUE THREAD

**Issue by davidmoshal** [displague/vagrant-linode#44]
vagrant plugin install vagrant-linode
Installing the 'vagrant-linode' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.0.0/net/protocol.rb:211:in `write': Socket is not connected (Errno::ENOTCONN)
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/protocol.rb:211:in `write0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/protocol.rb:185:in `block in write'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/protocol.rb:202:in `writing'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/protocol.rb:184:in `write'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http/generic_request.rb:325:in `write_header'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http/generic_request.rb:136:in `exec'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:1410:in `block in transport_request'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/vendor/net/http/persistent.rb:999:in `request'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher/downloader.rb:45:in `request'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher/downloader.rb:15:in `fetch'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher/dependency.rb:7:in `api_available?'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher.rb:135:in `block in use_api'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher.rb:135:in `reject!'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/fetcher.rb:135:in `use_api'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:320:in `select'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:320:in `api_fetchers'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:325:in `block in remote_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:324:in `remote_specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/source/rubygems.rb:81:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:211:in `block (2 levels) in index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `each'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:209:in `block in index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/index.rb:9:in `build'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:206:in `index'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:200:in `resolve'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:140:in `specs'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/definition.rb:129:in `resolve_remotely!'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/installer.rb:79:in `run'
	from /opt/vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/installer.rb:18:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:226:in `block in internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:284:in `block in with_isolated_gem'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/rubygems/user_interaction.rb:40:in `use_ui'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:283:in `with_isolated_gem'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:225:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/bundler.rb:92:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:72:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/action/install_gem.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/base.rb:14:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:32:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/install.rb:31:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/commands/plugin/command/root.rb:56:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:174:in `<main>'

**Comment by displague** [comment]
Can you try installing another plugin from the same machine. Nothing in this stack trace points to vagrant-linode itself. Is it possible you are behind a firewall or were experiencing an outtage at the time?

**Comment by CarlQLange** [comment]
I've hit this too, @davidmoshal what version of OSX are you on?

**Comment by CarlQLange** [comment]
I'm also getting this a lot:

```
Installing the 'vagrant-linode' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Network error while fetching https://rubygems.org/quick/Marshal.4.8/i18n-0.1.0.gemspec.rz

Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resol
ve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.Retr
ying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://bundler.rubygems.org/api/v1/dependencies?gems=bcryptRetrying dependency api due t
o error (3/4): Bundler::HTTPError Network error while fetching https://bundler.rubygems.org/api/v1/dependencies?gems=bcryptRetrying dependency api due to error (4/4): Bundler::H
TTPError Network error while fetching https://bundler.rubygems.org/api/v1/dependencies?gems=bcrypt 
```

**Comment by CarlQLange** [comment]
I suspect my error may have been due to using nonstandard DNS servers, or maybe IPv6 or something. Switched to a new network and no issues.

**Comment by displague** [comment]
Is this still a problem @davidmoshal?

Do these instructions (which I removed two revisions ago) help?

> **NOTE:** If you are using a Mac, and this plugin would not work caused by SSL certificate problem, You may need to specify certificate path explicitly. You can verify actual certificate path by running:
> 
> ```
> ruby -ropenssl -e "p OpenSSL::X509::DEFAULT_CERT_FILE"
> ```
> Then, add the following environment variable to your .bash_profile script and source it:
> 
> ```
> export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
> ```

**Comment by davidmoshal** [comment]
@displague I just tried this now and it worked fine:

```vagrant plugin install vagrant-linode```

However, I have to confess that I switched to Digital Ocean when I ran into the problem 3 weeks ago, though I still have several servers on Linode, which I'll try this on at some point.

Dave

**Comment by displague** [comment]
> though I still have several servers on Linode, which I'll try this on at some point

That statement sounds dangerous.  You would use vagrant-linode to create and manage new Vagrant governed Linodes, not interact with existing ones.

It sounds like this was an intermittent networking issue.  Please let me know this if the problem is reencountered.
