### ISSUE TITLE
Rsync__exclude doesn't work

### ISSUE THREAD

**Issue by maximead** [displague/vagrant-linode#45]
As per the doc, one should be able to exclude some subdirectories with the "rsync__exclude" option.

https://docs.vagrantup.com/v2/synced-folders/rsync.html

However, it does not seem to be working in vagrant Linode.

I think we coud replace
            # rsync over to the guest path using the ssh info
            command = [
              'rsync', '--verbose', '--archive', '-z', '--delete',
              '-e', "ssh -p #{ssh_info[:port]} -o StrictHostKeyChecking=no -i '#{key}'",
              hostpath,
              "#{ssh_info[:username]}@#{ssh_info[:host]}:#{guestpath}"]

With
            # Excludes
            excludes = ['.vagrant/', *Array(data[:rsync_excludes])]

            # rsync over to the guest path using the ssh info
            command = [
              'rsync', '--verbose', '--archive', '-z', '--delete',*excludes.map{|e|['--exclude', e]}.flatten,
              '-e', "ssh -p #{ssh_info[:port]} -o StrictHostKeyChecking=no -i '#{key}'",
              hostpath,
              "#{ssh_info[:username]}@#{ssh_info[:host]}:#{guestpath}"]

To have a similar fonctionality. (Inspired by https://github.com/mitchellh/vagrant-aws/pull/156/files#r7047175)

I tried to make/build a custom plugin and test it, but I don't know anything of Ruby and it's simply beyond my capacity. Maybe someone more knowledgeable would be able to make the fix?

Thank you!

**Comment by displague** [comment]
Corrected in v0.2.1.  Thanks.
