### ISSUE TITLE
API Error on linode.disk.create: [{"ERRORMESSAGE"=>"Size is required but was not passed in", "ERRORCODE"=>6}] (RuntimeError)

### ISSUE THREAD

**Issue by llob** [displague/vagrant-linode#74]
I am spuriously receiving this error when managing linodes via vagrant. Most of the time everything works as expected, but occasionally this happens. Any thoughts on how to debug?

> 
> ==> default: Created a new linode... 3245567, https://manager.linode.com/linodes/dashboard/jenkins-build-autoaif
> /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:87:in `parse': API Error on linode.disk.create: [{"ERRORMESSAGE"=>"Size is required but was not passed in", "ERRORCODE"=>6}] (RuntimeError)
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:80:in `error_check'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:72:in `call'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:62:in `block in make_call'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:63:in `make_call'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/linodeapi-1.0.1/lib/linodeapi/raw.rb:44:in `method_missing'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/create.rb:172:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/connect_linode.rb:31:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /var/lib/jenkins/.vagrant.d/gems/gems/vagrant-linode-0.2.8/lib/vagrant-linode/actions/message_not_created.rb:11:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/provision.rb:80:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/call.rb:53:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/warden.rb:34:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/builder.rb:116:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `block in run'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/util/busy.rb:19:in `busy'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/action/runner.rb:66:in `run'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:225:in `action_raw'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:200:in `block in action'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/environment.rb:567:in `lock'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `call'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/machine.rb:186:in `action'
> 	from /opt/vagrant/embedded/gems/gems/vagrant-1.8.7/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by displague** [comment]
I have an good authority that this was an intermittent issue with the API service.  It has been corrected.

Can you try again?

**Comment by llob** [comment]
As I mentioned, the error was intermittent, so it's a little hard to confirm.
I haven't observed the problem all day though, so it does look like it has resolved itself.

Thanks for getting back to me on this. I am closing the issue, and will reopen if it turns out not to resolved after all.

**Comment by al-v-in** [comment]
I've intermittently encountered this issue today. Sometimes it works fine, sometimes it will halt and show one of the following errors:

[{"ERRORMESSAGE"=>"LINODEID is required but was not passed in", "ERRORCODE"=>6}]

[{"ERRORMESSAGE"=>"Size is required but was not passed in", "ERRORCODE"=>6}]

**Comment by rmcintosh** [comment]
@al-v-in sorry! that should be resolved now - can you give it another go?
