### ISSUE TITLE
Vagrant 2.0.1 downgrade the vagrant-linode plugin to 0.1.2

### ISSUE THREAD

**Issue by pernico** [displague/vagrant-linode#80]
Hi,

I'm having a plugin version issue since I upgraded to the latest vagrant release.

Before the upgrade : 
- Vagrant release (1.8.1)
- Plugin vagrant-linode (0.2.8)

After the upgrade : 
- Vagrant release (2.0.1)
- Plugin vagrant-linode (0.1.2)

Has anybody experienced the same issue? Both Ubuntu Xenial and CentOS 7.4 Vagrant upgrade behavior is the same.

I tried with digitalocean's vagrant plugin to compare and it does take the latest release as expected, so it seems an issue with the vagrant-linode plugin somehow.

Thank you,

Nicolas

**Comment by displague** [comment]
I just pushed version 0.3.0 of the plugin.  Try `vagrant plugin update` fir Vagrant 2.0.1.

**Comment by displague** [comment]
Please reopen this issue if you can reproduce the problem after updating.
