### ISSUE TITLE
support volumes

### ISSUE THREAD

**Issue by cromega** [displague/vagrant-linode#82]
Hi,

I've been playing around with the code trying to hack support for [block storages](https://www.linode.com/docs/platform/how-to-use-block-storage-with-your-linode) into it.

The idea was that with something like this in the Vagrantfile:

```ruby
config.vm.provider :linode do |linode|
  linode.plan = "Linode 2048"
  linode.volumes = [
    {size: 1} # size is in gbs
  ]
end
```
vagrant would create and attach the volumes upon VM creation.

The aim is being able to **rebuild** a VM with some clever dance with detaching/reattaching volumes to preserve some OS state.

I realised that it would add significant complexity to certain actions. And then there are a few questions I'm not even sure I know the answer to.

When `vagrant up` is executed multiple times should it check that the volumes exist as well?

What happens to the volumes when the VM is destroyed? It would certainly be possible to run `vagrant up` again and then the plugin could reattach the volumes but it requires a change to the Vagrantfile because the VM definition would need to specify the volume IDs instead of the size.

An idea is  that `vagrant destroy` permanently destroys the volumes as well while `vagrant rebuild` does the detach volume - rebuild vm - attach volume cycle.

What are your thoughts?

**Comment by displague** [comment]
It is certainly possible to include Volumes via https://www.linode.com/api/volume .

I would want draw volume handling behavior from other vagrant provider plugins (from providers where volumes are charged and handled in a similar way) as the expectation should be the same.

Volumes could be created / attached / matched by using label (and checking for the existence of that label).  I think `vagrant linode volume-destroy {label}` and `vagrant linode volume-create {label}` might be additions needed to separate the use case here (again, I would look for existing examples in other providers for naming).

I'd be pretty uncomfortable about a Vagrant Linode destroy also destroying the reusable volume, unless it was a non-default option provided (for rebuild or regular destroy).

**Comment by displague** [comment]
If you have a branch or PR in the works, please link it here.

**Comment by cromega** [comment]
@displague I decided against implementing commands for creating/deleting volumes. I'm happy to argue about it, the Tl;DR is that doing other things would be mixing in other use-cases such as terraform or the linode CLI.

Most of the volume handling functionality is done, you can check the progress [here](https://github.com/cromega/vagrant-linode/tree/volume-handling). I will send a PR soon unless you disagree with my approach :)
