### ISSUE TITLE
api exception details are not displayed

### ISSUE THREAD

**Issue by cromega** [displague/vagrant-linode#83]
Hi,

When the Linode API responds with an error the details are not printed anywhere. This is what I see:

```
/home/crome/.vagrant.d/gems/2.3.3/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:23:in `parse': API Error encountered (LinodeAPI::APIError)
	from /home/crome/.vagrant.d/gems/2.3.3/gems/linodeapi-2.0.1/lib/linodeapi/helpers.rb:10:in `error_check'
*snip*
```

The useful bit with the response containing the error message(s) is in `APIError#details` coming from the linodeapi gem. It would be great to capture the exceptions, print the details before letting vagrant die.

**Comment by displague** [comment]
I'll be reviewing your volume storage PR over this next week.  Once merged, I'll include this fix and the volumes support under the next built/released/tagged version.

Thanks for all your help with this!
